//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michael/Repos/UrtLib/MapLib/Parser/Map.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	#pragma warning disable 3021
    using System.Globalization;
    using MapLib;
    using MapLib.Elements;
    using MapLib.Geometry;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMapListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MapBaseListener : IMapListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMap([NotNull] MapParser.MapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMap([NotNull] MapParser.MapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntity([NotNull] MapParser.EntityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntity([NotNull] MapParser.EntityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.entityKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityKey([NotNull] MapParser.EntityKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.entityKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityKey([NotNull] MapParser.EntityKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.entityElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityElement([NotNull] MapParser.EntityElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.entityElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityElement([NotNull] MapParser.EntityElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.brushElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBrushElement([NotNull] MapParser.BrushElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.brushElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBrushElement([NotNull] MapParser.BrushElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.brushFace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBrushFace([NotNull] MapParser.BrushFaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.brushFace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBrushFace([NotNull] MapParser.BrushFaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.patchElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPatchElement([NotNull] MapParser.PatchElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.patchElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPatchElement([NotNull] MapParser.PatchElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.patchVertex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPatchVertex([NotNull] MapParser.PatchVertexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.patchVertex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPatchVertex([NotNull] MapParser.PatchVertexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.keyValueParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValueParam([NotNull] MapParser.KeyValueParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.keyValueParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValueParam([NotNull] MapParser.KeyValueParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.pathParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathParam([NotNull] MapParser.PathParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.pathParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathParam([NotNull] MapParser.PathParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.intParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntParam([NotNull] MapParser.IntParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.intParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntParam([NotNull] MapParser.IntParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.numberParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberParam([NotNull] MapParser.NumberParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.numberParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberParam([NotNull] MapParser.NumberParamContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
