//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michael/Repos/UrtLib/MapLib/Parser/Map.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	#pragma warning disable 3021
    using System.Globalization;
    using MapLib;
    using MapLib.Elements;
    using MapLib.Geometry;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MapParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IMapListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMap([NotNull] MapParser.MapContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMap([NotNull] MapParser.MapContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.entity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntity([NotNull] MapParser.EntityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.entity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntity([NotNull] MapParser.EntityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.entityKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityKey([NotNull] MapParser.EntityKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.entityKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityKey([NotNull] MapParser.EntityKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.entityElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityElement([NotNull] MapParser.EntityElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.entityElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityElement([NotNull] MapParser.EntityElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.brushElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrushElement([NotNull] MapParser.BrushElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.brushElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrushElement([NotNull] MapParser.BrushElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.brushFace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrushFace([NotNull] MapParser.BrushFaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.brushFace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrushFace([NotNull] MapParser.BrushFaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.patchElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatchElement([NotNull] MapParser.PatchElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.patchElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatchElement([NotNull] MapParser.PatchElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.patchVertex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatchVertex([NotNull] MapParser.PatchVertexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.patchVertex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatchVertex([NotNull] MapParser.PatchVertexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.keyValueParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValueParam([NotNull] MapParser.KeyValueParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.keyValueParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValueParam([NotNull] MapParser.KeyValueParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.pathParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathParam([NotNull] MapParser.PathParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.pathParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathParam([NotNull] MapParser.PathParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.intParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntParam([NotNull] MapParser.IntParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.intParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntParam([NotNull] MapParser.IntParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapParser.numberParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberParam([NotNull] MapParser.NumberParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapParser.numberParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberParam([NotNull] MapParser.NumberParamContext context);
}
