//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michael/Repos/UrtLib/MapLib/Parser/Map.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	#pragma warning disable 3021
    using System.Globalization;
    using MapLib;
    using MapLib.Elements;
    using MapLib.Geometry;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MapParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IMapVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap([NotNull] MapParser.MapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.entity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity([NotNull] MapParser.EntityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.entityKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityKey([NotNull] MapParser.EntityKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.entityElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityElement([NotNull] MapParser.EntityElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.brushElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBrushElement([NotNull] MapParser.BrushElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.brushFace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBrushFace([NotNull] MapParser.BrushFaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.patchElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatchElement([NotNull] MapParser.PatchElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.patchVertex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatchVertex([NotNull] MapParser.PatchVertexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.keyValueParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyValueParam([NotNull] MapParser.KeyValueParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.pathParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathParam([NotNull] MapParser.PathParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.intParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntParam([NotNull] MapParser.IntParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapParser.numberParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberParam([NotNull] MapParser.NumberParamContext context);
}
