//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michael/Repos/UrtLib/ShaderLib/Parser/Shader.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	#pragma warning disable 3021
    using System.Globalization;
	using ShaderLib;
	using ShaderLib.Elements;
    using ShaderLib.Elements.Directives;
    using ShaderLib.Elements.Directives.Attributes;
    using ShaderLib.Elements.Directives.ShaderDirectives;
    using ShaderLib.Elements.Directives.ShaderDirectives.General;
    using ShaderLib.Elements.Directives.ShaderDirectives.Q3Map;
    using ShaderLib.Elements.Directives.ShaderDirectives.Qer;
    using ShaderLib.Elements.Directives.StageDirectives;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ShaderParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IShaderVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.shaderList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShaderList([NotNull] ShaderParser.ShaderListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.shader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShader([NotNull] ShaderParser.ShaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.stage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStage([NotNull] ShaderParser.StageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.shaderDirectiveList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShaderDirectiveList([NotNull] ShaderParser.ShaderDirectiveListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.stageList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStageList([NotNull] ShaderParser.StageListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.stageDirectiveList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStageDirectiveList([NotNull] ShaderParser.StageDirectiveListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.shaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShaderDirective([NotNull] ShaderParser.ShaderDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.generalDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralDirective([NotNull] ShaderParser.GeneralDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.cullDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCullDirective([NotNull] ShaderParser.CullDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.deformVertexesDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeformVertexesDirective([NotNull] ShaderParser.DeformVertexesDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.fogParmsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFogParmsDirective([NotNull] ShaderParser.FogParmsDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.noMipMapsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoMipMapsDirective([NotNull] ShaderParser.NoMipMapsDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.noPicMipDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPicMipDirective([NotNull] ShaderParser.NoPicMipDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.polygonOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPolygonOffsetDirective([NotNull] ShaderParser.PolygonOffsetDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.portalDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPortalDirective([NotNull] ShaderParser.PortalDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.skyParmsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkyParmsDirective([NotNull] ShaderParser.SkyParmsDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.sortDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortDirective([NotNull] ShaderParser.SortDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.tessSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTessSizeDirective([NotNull] ShaderParser.TessSizeDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.lightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLightDirective([NotNull] ShaderParser.LightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.entityMergableDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityMergableDirective([NotNull] ShaderParser.EntityMergableDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.surfaceParmDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSurfaceParmDirective([NotNull] ShaderParser.SurfaceParmDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapDirective([NotNull] ShaderParser.Q3mapDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapAlphaGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapAlphaGenDirective([NotNull] ShaderParser.Q3mapAlphaGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapAlphaModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapAlphaModDirective([NotNull] ShaderParser.Q3mapAlphaModDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapBackShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapBackShaderDirective([NotNull] ShaderParser.Q3mapBackShaderDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapBackSplashDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapBackSplashDirective([NotNull] ShaderParser.Q3mapBackSplashDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapBaseShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapBaseShaderDirective([NotNull] ShaderParser.Q3mapBaseShaderDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapBounceDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapBounceDirective([NotNull] ShaderParser.Q3mapBounceDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapBounceScaleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapBounceScaleDirective([NotNull] ShaderParser.Q3mapBounceScaleDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapClipModelDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapClipModelDirective([NotNull] ShaderParser.Q3mapClipModelDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapCloneShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapCloneShaderDirective([NotNull] ShaderParser.Q3mapCloneShaderDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapColorGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapColorGenDirective([NotNull] ShaderParser.Q3mapColorGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapColorModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapColorModDirective([NotNull] ShaderParser.Q3mapColorModDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapFancyWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapFancyWaterDirective([NotNull] ShaderParser.Q3mapFancyWaterDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapFogDirDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapFogDirDirective([NotNull] ShaderParser.Q3mapFogDirDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapForceMetaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapForceMetaDirective([NotNull] ShaderParser.Q3mapForceMetaDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapForceSunLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapForceSunLightDirective([NotNull] ShaderParser.Q3mapForceSunLightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapFurDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapFurDirective([NotNull] ShaderParser.Q3mapFurDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapGlobalTextureDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapGlobalTextureDirective([NotNull] ShaderParser.Q3mapGlobalTextureDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapIndexedDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapIndexedDirective([NotNull] ShaderParser.Q3mapIndexedDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapInvertDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapInvertDirective([NotNull] ShaderParser.Q3mapInvertDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightImageDirective([NotNull] ShaderParser.Q3mapLightImageDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapAxisDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapAxisDirective([NotNull] ShaderParser.Q3mapLightmapAxisDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapBrightnessDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapBrightnessDirective([NotNull] ShaderParser.Q3mapLightmapBrightnessDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapFilterRadiusDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapFilterRadiusDirective([NotNull] ShaderParser.Q3mapLightmapFilterRadiusDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapGammaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapGammaDirective([NotNull] ShaderParser.Q3mapLightmapGammaDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapMergableDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapMergableDirective([NotNull] ShaderParser.Q3mapLightmapMergableDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapSampleOffsetDirective([NotNull] ShaderParser.Q3mapLightmapSampleOffsetDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapSampleSizeDirective([NotNull] ShaderParser.Q3mapLightmapSampleSizeDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightmapSizeDirective([NotNull] ShaderParser.Q3mapLightmapSizeDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightRGBDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightRGBDirective([NotNull] ShaderParser.Q3mapLightRGBDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightStyleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightStyleDirective([NotNull] ShaderParser.Q3mapLightStyleDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapLightSubdivideDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapLightSubdivideDirective([NotNull] ShaderParser.Q3mapLightSubdivideDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoClipDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoClipDirective([NotNull] ShaderParser.Q3mapNoClipDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoFastDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoFastDirective([NotNull] ShaderParser.Q3mapNoFastDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoFogDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoFogDirective([NotNull] ShaderParser.Q3mapNoFogDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoLightmapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoLightmapDirective([NotNull] ShaderParser.Q3mapNoLightmapDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNonPlanarDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNonPlanarDirective([NotNull] ShaderParser.Q3mapNonPlanarDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNormalImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNormalImageDirective([NotNull] ShaderParser.Q3mapNormalImageDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoTJuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoTJuncDirective([NotNull] ShaderParser.Q3mapNoTJuncDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoVertexLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoVertexLightDirective([NotNull] ShaderParser.Q3mapNoVertexLightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoVertexShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoVertexShadowsDirective([NotNull] ShaderParser.Q3mapNoVertexShadowsDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapOffsetDirective([NotNull] ShaderParser.Q3mapOffsetDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapPatchShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapPatchShadowsDirective([NotNull] ShaderParser.Q3mapPatchShadowsDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapRemapShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapRemapShaderDirective([NotNull] ShaderParser.Q3mapRemapShaderDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapRGBGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapRGBGenDirective([NotNull] ShaderParser.Q3mapRGBGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapRGBModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapRGBModDirective([NotNull] ShaderParser.Q3mapRGBModDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapShadeAngleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapShadeAngleDirective([NotNull] ShaderParser.Q3mapShadeAngleDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapSkyLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapSkyLightDirective([NotNull] ShaderParser.Q3mapSkyLightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapSplotchFixDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapSplotchFixDirective([NotNull] ShaderParser.Q3mapSplotchFixDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapStyleMarkerDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapStyleMarkerDirective([NotNull] ShaderParser.Q3mapStyleMarkerDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapStyleMarker2Directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapStyleMarker2Directive([NotNull] ShaderParser.Q3mapStyleMarker2DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapSunDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapSunDirective([NotNull] ShaderParser.Q3mapSunDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapSunExtDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapSunExtDirective([NotNull] ShaderParser.Q3mapSunExtDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapSurfaceLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapSurfaceLightDirective([NotNull] ShaderParser.Q3mapSurfaceLightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapSurfaceModelDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapSurfaceModelDirective([NotNull] ShaderParser.Q3mapSurfaceModelDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapTcGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapTcGenDirective([NotNull] ShaderParser.Q3mapTcGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapTcModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapTcModDirective([NotNull] ShaderParser.Q3mapTcModDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapTerrainDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapTerrainDirective([NotNull] ShaderParser.Q3mapTerrainDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapTessSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapTessSizeDirective([NotNull] ShaderParser.Q3mapTessSizeDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapTextureSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapTextureSizeDirective([NotNull] ShaderParser.Q3mapTextureSizeDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapTraceLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapTraceLightDirective([NotNull] ShaderParser.Q3mapTraceLightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapVertexScaleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapVertexScaleDirective([NotNull] ShaderParser.Q3mapVertexScaleDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapVertexShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapVertexShadowsDirective([NotNull] ShaderParser.Q3mapVertexShadowsDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapVLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapVLightDirective([NotNull] ShaderParser.Q3mapVLightDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapNoFancyWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapNoFancyWaterDirective([NotNull] ShaderParser.Q3mapNoFancyWaterDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3mapCheapWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3mapCheapWaterDirective([NotNull] ShaderParser.Q3mapCheapWaterDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.editorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEditorDirective([NotNull] ShaderParser.EditorDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.qerEditorImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQerEditorImageDirective([NotNull] ShaderParser.QerEditorImageDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.qerNoCarveDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQerNoCarveDirective([NotNull] ShaderParser.QerNoCarveDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.qerTransDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQerTransDirective([NotNull] ShaderParser.QerTransDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.qerAlphaFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQerAlphaFuncDirective([NotNull] ShaderParser.QerAlphaFuncDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.stageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStageDirective([NotNull] ShaderParser.StageDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.mapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapDirective([NotNull] ShaderParser.MapDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.clampMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClampMapDirective([NotNull] ShaderParser.ClampMapDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.animMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnimMapDirective([NotNull] ShaderParser.AnimMapDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.videoMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVideoMapDirective([NotNull] ShaderParser.VideoMapDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.blendFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlendFuncDirective([NotNull] ShaderParser.BlendFuncDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.rGBGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRGBGenDirective([NotNull] ShaderParser.RGBGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.alphaGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlphaGenDirective([NotNull] ShaderParser.AlphaGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.tcGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTcGenDirective([NotNull] ShaderParser.TcGenDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.tcModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTcModDirective([NotNull] ShaderParser.TcModDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.depthFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDepthFuncDirective([NotNull] ShaderParser.DepthFuncDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.depthWriteDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDepthWriteDirective([NotNull] ShaderParser.DepthWriteDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.detailDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDetailDirective([NotNull] ShaderParser.DetailDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.alphaFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlphaFuncDirective([NotNull] ShaderParser.AlphaFuncDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.boolParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolParam([NotNull] ShaderParser.BoolParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.intParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntParam([NotNull] ShaderParser.IntParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.numberParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberParam([NotNull] ShaderParser.NumberParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.pathParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathParam([NotNull] ShaderParser.PathParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.cullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCullType([NotNull] ShaderParser.CullTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.waveFormFunctionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaveFormFunctionType([NotNull] ShaderParser.WaveFormFunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.sortType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortType([NotNull] ShaderParser.SortTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.surfaceParmType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSurfaceParmType([NotNull] ShaderParser.SurfaceParmTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.qer_alphaFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQer_alphaFuncType([NotNull] ShaderParser.Qer_alphaFuncTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.q3map_lightmapAxisType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ3map_lightmapAxisType([NotNull] ShaderParser.Q3map_lightmapAxisTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.blendFuncSimplifiedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlendFuncSimplifiedType([NotNull] ShaderParser.BlendFuncSimplifiedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.blendFuncExplicitSrcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlendFuncExplicitSrcType([NotNull] ShaderParser.BlendFuncExplicitSrcTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.blendFuncExplicitDestType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlendFuncExplicitDestType([NotNull] ShaderParser.BlendFuncExplicitDestTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.depthFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDepthFuncType([NotNull] ShaderParser.DepthFuncTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ShaderParser.alphaFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlphaFuncType([NotNull] ShaderParser.AlphaFuncTypeContext context);
}
