//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michael/Repos/UrtLib/ShaderLib/Parser/Shader.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	#pragma warning disable 3021
    using System.Globalization;
	using ShaderLib;
	using ShaderLib.Elements;
    using ShaderLib.Elements.Directives;
    using ShaderLib.Elements.Directives.Attributes;
    using ShaderLib.Elements.Directives.ShaderDirectives;
    using ShaderLib.Elements.Directives.ShaderDirectives.General;
    using ShaderLib.Elements.Directives.ShaderDirectives.Q3Map;
    using ShaderLib.Elements.Directives.ShaderDirectives.Qer;
    using ShaderLib.Elements.Directives.StageDirectives;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IShaderListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ShaderBaseListener : IShaderListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shaderList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderList([NotNull] ShaderParser.ShaderListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shaderList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderList([NotNull] ShaderParser.ShaderListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShader([NotNull] ShaderParser.ShaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShader([NotNull] ShaderParser.ShaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage([NotNull] ShaderParser.StageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage([NotNull] ShaderParser.StageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shaderDirectiveList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderDirectiveList([NotNull] ShaderParser.ShaderDirectiveListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shaderDirectiveList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderDirectiveList([NotNull] ShaderParser.ShaderDirectiveListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stageList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStageList([NotNull] ShaderParser.StageListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stageList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStageList([NotNull] ShaderParser.StageListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stageDirectiveList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStageDirectiveList([NotNull] ShaderParser.StageDirectiveListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stageDirectiveList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStageDirectiveList([NotNull] ShaderParser.StageDirectiveListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderDirective([NotNull] ShaderParser.ShaderDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderDirective([NotNull] ShaderParser.ShaderDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.generalDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralDirective([NotNull] ShaderParser.GeneralDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.generalDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralDirective([NotNull] ShaderParser.GeneralDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.cullDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCullDirective([NotNull] ShaderParser.CullDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.cullDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCullDirective([NotNull] ShaderParser.CullDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.deformVertexesDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeformVertexesDirective([NotNull] ShaderParser.DeformVertexesDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.deformVertexesDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeformVertexesDirective([NotNull] ShaderParser.DeformVertexesDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.fogParmsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFogParmsDirective([NotNull] ShaderParser.FogParmsDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.fogParmsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFogParmsDirective([NotNull] ShaderParser.FogParmsDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.noMipMapsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoMipMapsDirective([NotNull] ShaderParser.NoMipMapsDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.noMipMapsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoMipMapsDirective([NotNull] ShaderParser.NoMipMapsDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.noPicMipDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoPicMipDirective([NotNull] ShaderParser.NoPicMipDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.noPicMipDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoPicMipDirective([NotNull] ShaderParser.NoPicMipDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.polygonOffsetDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPolygonOffsetDirective([NotNull] ShaderParser.PolygonOffsetDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.polygonOffsetDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPolygonOffsetDirective([NotNull] ShaderParser.PolygonOffsetDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.portalDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPortalDirective([NotNull] ShaderParser.PortalDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.portalDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPortalDirective([NotNull] ShaderParser.PortalDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.skyParmsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkyParmsDirective([NotNull] ShaderParser.SkyParmsDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.skyParmsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkyParmsDirective([NotNull] ShaderParser.SkyParmsDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.sortDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortDirective([NotNull] ShaderParser.SortDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.sortDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortDirective([NotNull] ShaderParser.SortDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.tessSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTessSizeDirective([NotNull] ShaderParser.TessSizeDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.tessSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTessSizeDirective([NotNull] ShaderParser.TessSizeDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.lightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLightDirective([NotNull] ShaderParser.LightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.lightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLightDirective([NotNull] ShaderParser.LightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.entityMergableDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityMergableDirective([NotNull] ShaderParser.EntityMergableDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.entityMergableDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityMergableDirective([NotNull] ShaderParser.EntityMergableDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.surfaceParmDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSurfaceParmDirective([NotNull] ShaderParser.SurfaceParmDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.surfaceParmDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSurfaceParmDirective([NotNull] ShaderParser.SurfaceParmDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapDirective([NotNull] ShaderParser.Q3mapDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapDirective([NotNull] ShaderParser.Q3mapDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapAlphaGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapAlphaGenDirective([NotNull] ShaderParser.Q3mapAlphaGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapAlphaGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapAlphaGenDirective([NotNull] ShaderParser.Q3mapAlphaGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapAlphaModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapAlphaModDirective([NotNull] ShaderParser.Q3mapAlphaModDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapAlphaModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapAlphaModDirective([NotNull] ShaderParser.Q3mapAlphaModDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBackShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapBackShaderDirective([NotNull] ShaderParser.Q3mapBackShaderDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBackShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapBackShaderDirective([NotNull] ShaderParser.Q3mapBackShaderDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBackSplashDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapBackSplashDirective([NotNull] ShaderParser.Q3mapBackSplashDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBackSplashDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapBackSplashDirective([NotNull] ShaderParser.Q3mapBackSplashDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBaseShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapBaseShaderDirective([NotNull] ShaderParser.Q3mapBaseShaderDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBaseShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapBaseShaderDirective([NotNull] ShaderParser.Q3mapBaseShaderDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBounceDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapBounceDirective([NotNull] ShaderParser.Q3mapBounceDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBounceDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapBounceDirective([NotNull] ShaderParser.Q3mapBounceDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBounceScaleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapBounceScaleDirective([NotNull] ShaderParser.Q3mapBounceScaleDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBounceScaleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapBounceScaleDirective([NotNull] ShaderParser.Q3mapBounceScaleDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapClipModelDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapClipModelDirective([NotNull] ShaderParser.Q3mapClipModelDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapClipModelDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapClipModelDirective([NotNull] ShaderParser.Q3mapClipModelDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapCloneShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapCloneShaderDirective([NotNull] ShaderParser.Q3mapCloneShaderDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapCloneShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapCloneShaderDirective([NotNull] ShaderParser.Q3mapCloneShaderDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapColorGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapColorGenDirective([NotNull] ShaderParser.Q3mapColorGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapColorGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapColorGenDirective([NotNull] ShaderParser.Q3mapColorGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapColorModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapColorModDirective([NotNull] ShaderParser.Q3mapColorModDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapColorModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapColorModDirective([NotNull] ShaderParser.Q3mapColorModDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapFancyWaterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapFancyWaterDirective([NotNull] ShaderParser.Q3mapFancyWaterDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapFancyWaterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapFancyWaterDirective([NotNull] ShaderParser.Q3mapFancyWaterDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapFogDirDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapFogDirDirective([NotNull] ShaderParser.Q3mapFogDirDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapFogDirDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapFogDirDirective([NotNull] ShaderParser.Q3mapFogDirDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapForceMetaDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapForceMetaDirective([NotNull] ShaderParser.Q3mapForceMetaDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapForceMetaDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapForceMetaDirective([NotNull] ShaderParser.Q3mapForceMetaDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapForceSunLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapForceSunLightDirective([NotNull] ShaderParser.Q3mapForceSunLightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapForceSunLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapForceSunLightDirective([NotNull] ShaderParser.Q3mapForceSunLightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapFurDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapFurDirective([NotNull] ShaderParser.Q3mapFurDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapFurDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapFurDirective([NotNull] ShaderParser.Q3mapFurDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapGlobalTextureDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapGlobalTextureDirective([NotNull] ShaderParser.Q3mapGlobalTextureDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapGlobalTextureDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapGlobalTextureDirective([NotNull] ShaderParser.Q3mapGlobalTextureDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapIndexedDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapIndexedDirective([NotNull] ShaderParser.Q3mapIndexedDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapIndexedDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapIndexedDirective([NotNull] ShaderParser.Q3mapIndexedDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapInvertDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapInvertDirective([NotNull] ShaderParser.Q3mapInvertDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapInvertDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapInvertDirective([NotNull] ShaderParser.Q3mapInvertDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightImageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightImageDirective([NotNull] ShaderParser.Q3mapLightImageDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightImageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightImageDirective([NotNull] ShaderParser.Q3mapLightImageDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapAxisDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapAxisDirective([NotNull] ShaderParser.Q3mapLightmapAxisDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapAxisDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapAxisDirective([NotNull] ShaderParser.Q3mapLightmapAxisDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapBrightnessDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapBrightnessDirective([NotNull] ShaderParser.Q3mapLightmapBrightnessDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapBrightnessDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapBrightnessDirective([NotNull] ShaderParser.Q3mapLightmapBrightnessDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapFilterRadiusDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapFilterRadiusDirective([NotNull] ShaderParser.Q3mapLightmapFilterRadiusDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapFilterRadiusDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapFilterRadiusDirective([NotNull] ShaderParser.Q3mapLightmapFilterRadiusDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapGammaDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapGammaDirective([NotNull] ShaderParser.Q3mapLightmapGammaDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapGammaDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapGammaDirective([NotNull] ShaderParser.Q3mapLightmapGammaDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapMergableDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapMergableDirective([NotNull] ShaderParser.Q3mapLightmapMergableDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapMergableDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapMergableDirective([NotNull] ShaderParser.Q3mapLightmapMergableDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleOffsetDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapSampleOffsetDirective([NotNull] ShaderParser.Q3mapLightmapSampleOffsetDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleOffsetDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapSampleOffsetDirective([NotNull] ShaderParser.Q3mapLightmapSampleOffsetDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapSampleSizeDirective([NotNull] ShaderParser.Q3mapLightmapSampleSizeDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapSampleSizeDirective([NotNull] ShaderParser.Q3mapLightmapSampleSizeDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightmapSizeDirective([NotNull] ShaderParser.Q3mapLightmapSizeDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightmapSizeDirective([NotNull] ShaderParser.Q3mapLightmapSizeDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightRGBDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightRGBDirective([NotNull] ShaderParser.Q3mapLightRGBDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightRGBDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightRGBDirective([NotNull] ShaderParser.Q3mapLightRGBDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightStyleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightStyleDirective([NotNull] ShaderParser.Q3mapLightStyleDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightStyleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightStyleDirective([NotNull] ShaderParser.Q3mapLightStyleDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightSubdivideDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapLightSubdivideDirective([NotNull] ShaderParser.Q3mapLightSubdivideDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightSubdivideDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapLightSubdivideDirective([NotNull] ShaderParser.Q3mapLightSubdivideDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoClipDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoClipDirective([NotNull] ShaderParser.Q3mapNoClipDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoClipDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoClipDirective([NotNull] ShaderParser.Q3mapNoClipDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoFastDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoFastDirective([NotNull] ShaderParser.Q3mapNoFastDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoFastDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoFastDirective([NotNull] ShaderParser.Q3mapNoFastDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoFogDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoFogDirective([NotNull] ShaderParser.Q3mapNoFogDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoFogDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoFogDirective([NotNull] ShaderParser.Q3mapNoFogDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoLightmapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoLightmapDirective([NotNull] ShaderParser.Q3mapNoLightmapDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoLightmapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoLightmapDirective([NotNull] ShaderParser.Q3mapNoLightmapDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNonPlanarDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNonPlanarDirective([NotNull] ShaderParser.Q3mapNonPlanarDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNonPlanarDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNonPlanarDirective([NotNull] ShaderParser.Q3mapNonPlanarDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNormalImageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNormalImageDirective([NotNull] ShaderParser.Q3mapNormalImageDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNormalImageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNormalImageDirective([NotNull] ShaderParser.Q3mapNormalImageDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoTJuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoTJuncDirective([NotNull] ShaderParser.Q3mapNoTJuncDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoTJuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoTJuncDirective([NotNull] ShaderParser.Q3mapNoTJuncDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoVertexLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoVertexLightDirective([NotNull] ShaderParser.Q3mapNoVertexLightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoVertexLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoVertexLightDirective([NotNull] ShaderParser.Q3mapNoVertexLightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoVertexShadowsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoVertexShadowsDirective([NotNull] ShaderParser.Q3mapNoVertexShadowsDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoVertexShadowsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoVertexShadowsDirective([NotNull] ShaderParser.Q3mapNoVertexShadowsDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapOffsetDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapOffsetDirective([NotNull] ShaderParser.Q3mapOffsetDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapOffsetDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapOffsetDirective([NotNull] ShaderParser.Q3mapOffsetDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapPatchShadowsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapPatchShadowsDirective([NotNull] ShaderParser.Q3mapPatchShadowsDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapPatchShadowsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapPatchShadowsDirective([NotNull] ShaderParser.Q3mapPatchShadowsDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapRemapShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapRemapShaderDirective([NotNull] ShaderParser.Q3mapRemapShaderDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapRemapShaderDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapRemapShaderDirective([NotNull] ShaderParser.Q3mapRemapShaderDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapRGBGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapRGBGenDirective([NotNull] ShaderParser.Q3mapRGBGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapRGBGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapRGBGenDirective([NotNull] ShaderParser.Q3mapRGBGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapRGBModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapRGBModDirective([NotNull] ShaderParser.Q3mapRGBModDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapRGBModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapRGBModDirective([NotNull] ShaderParser.Q3mapRGBModDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapShadeAngleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapShadeAngleDirective([NotNull] ShaderParser.Q3mapShadeAngleDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapShadeAngleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapShadeAngleDirective([NotNull] ShaderParser.Q3mapShadeAngleDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSkyLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapSkyLightDirective([NotNull] ShaderParser.Q3mapSkyLightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSkyLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapSkyLightDirective([NotNull] ShaderParser.Q3mapSkyLightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSplotchFixDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapSplotchFixDirective([NotNull] ShaderParser.Q3mapSplotchFixDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSplotchFixDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapSplotchFixDirective([NotNull] ShaderParser.Q3mapSplotchFixDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapStyleMarkerDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapStyleMarkerDirective([NotNull] ShaderParser.Q3mapStyleMarkerDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapStyleMarkerDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapStyleMarkerDirective([NotNull] ShaderParser.Q3mapStyleMarkerDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapStyleMarker2Directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapStyleMarker2Directive([NotNull] ShaderParser.Q3mapStyleMarker2DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapStyleMarker2Directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapStyleMarker2Directive([NotNull] ShaderParser.Q3mapStyleMarker2DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSunDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapSunDirective([NotNull] ShaderParser.Q3mapSunDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSunDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapSunDirective([NotNull] ShaderParser.Q3mapSunDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSunExtDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapSunExtDirective([NotNull] ShaderParser.Q3mapSunExtDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSunExtDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapSunExtDirective([NotNull] ShaderParser.Q3mapSunExtDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSurfaceLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapSurfaceLightDirective([NotNull] ShaderParser.Q3mapSurfaceLightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSurfaceLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapSurfaceLightDirective([NotNull] ShaderParser.Q3mapSurfaceLightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSurfaceModelDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapSurfaceModelDirective([NotNull] ShaderParser.Q3mapSurfaceModelDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSurfaceModelDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapSurfaceModelDirective([NotNull] ShaderParser.Q3mapSurfaceModelDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTcGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapTcGenDirective([NotNull] ShaderParser.Q3mapTcGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTcGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapTcGenDirective([NotNull] ShaderParser.Q3mapTcGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTcModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapTcModDirective([NotNull] ShaderParser.Q3mapTcModDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTcModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapTcModDirective([NotNull] ShaderParser.Q3mapTcModDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTerrainDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapTerrainDirective([NotNull] ShaderParser.Q3mapTerrainDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTerrainDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapTerrainDirective([NotNull] ShaderParser.Q3mapTerrainDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTessSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapTessSizeDirective([NotNull] ShaderParser.Q3mapTessSizeDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTessSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapTessSizeDirective([NotNull] ShaderParser.Q3mapTessSizeDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTextureSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapTextureSizeDirective([NotNull] ShaderParser.Q3mapTextureSizeDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTextureSizeDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapTextureSizeDirective([NotNull] ShaderParser.Q3mapTextureSizeDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTraceLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapTraceLightDirective([NotNull] ShaderParser.Q3mapTraceLightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTraceLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapTraceLightDirective([NotNull] ShaderParser.Q3mapTraceLightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapVertexScaleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapVertexScaleDirective([NotNull] ShaderParser.Q3mapVertexScaleDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapVertexScaleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapVertexScaleDirective([NotNull] ShaderParser.Q3mapVertexScaleDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapVertexShadowsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapVertexShadowsDirective([NotNull] ShaderParser.Q3mapVertexShadowsDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapVertexShadowsDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapVertexShadowsDirective([NotNull] ShaderParser.Q3mapVertexShadowsDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapVLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapVLightDirective([NotNull] ShaderParser.Q3mapVLightDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapVLightDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapVLightDirective([NotNull] ShaderParser.Q3mapVLightDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoFancyWaterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapNoFancyWaterDirective([NotNull] ShaderParser.Q3mapNoFancyWaterDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoFancyWaterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapNoFancyWaterDirective([NotNull] ShaderParser.Q3mapNoFancyWaterDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapCheapWaterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3mapCheapWaterDirective([NotNull] ShaderParser.Q3mapCheapWaterDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapCheapWaterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3mapCheapWaterDirective([NotNull] ShaderParser.Q3mapCheapWaterDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.editorDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEditorDirective([NotNull] ShaderParser.EditorDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.editorDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEditorDirective([NotNull] ShaderParser.EditorDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerEditorImageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQerEditorImageDirective([NotNull] ShaderParser.QerEditorImageDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerEditorImageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQerEditorImageDirective([NotNull] ShaderParser.QerEditorImageDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerNoCarveDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQerNoCarveDirective([NotNull] ShaderParser.QerNoCarveDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerNoCarveDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQerNoCarveDirective([NotNull] ShaderParser.QerNoCarveDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerTransDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQerTransDirective([NotNull] ShaderParser.QerTransDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerTransDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQerTransDirective([NotNull] ShaderParser.QerTransDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerAlphaFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQerAlphaFuncDirective([NotNull] ShaderParser.QerAlphaFuncDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerAlphaFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQerAlphaFuncDirective([NotNull] ShaderParser.QerAlphaFuncDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStageDirective([NotNull] ShaderParser.StageDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stageDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStageDirective([NotNull] ShaderParser.StageDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.mapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapDirective([NotNull] ShaderParser.MapDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.mapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapDirective([NotNull] ShaderParser.MapDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.clampMapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClampMapDirective([NotNull] ShaderParser.ClampMapDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.clampMapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClampMapDirective([NotNull] ShaderParser.ClampMapDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.animMapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnimMapDirective([NotNull] ShaderParser.AnimMapDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.animMapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnimMapDirective([NotNull] ShaderParser.AnimMapDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.videoMapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVideoMapDirective([NotNull] ShaderParser.VideoMapDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.videoMapDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVideoMapDirective([NotNull] ShaderParser.VideoMapDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlendFuncDirective([NotNull] ShaderParser.BlendFuncDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlendFuncDirective([NotNull] ShaderParser.BlendFuncDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.rGBGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRGBGenDirective([NotNull] ShaderParser.RGBGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.rGBGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRGBGenDirective([NotNull] ShaderParser.RGBGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.alphaGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlphaGenDirective([NotNull] ShaderParser.AlphaGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.alphaGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlphaGenDirective([NotNull] ShaderParser.AlphaGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.tcGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTcGenDirective([NotNull] ShaderParser.TcGenDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.tcGenDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTcGenDirective([NotNull] ShaderParser.TcGenDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.tcModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTcModDirective([NotNull] ShaderParser.TcModDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.tcModDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTcModDirective([NotNull] ShaderParser.TcModDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.depthFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDepthFuncDirective([NotNull] ShaderParser.DepthFuncDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.depthFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDepthFuncDirective([NotNull] ShaderParser.DepthFuncDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.depthWriteDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDepthWriteDirective([NotNull] ShaderParser.DepthWriteDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.depthWriteDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDepthWriteDirective([NotNull] ShaderParser.DepthWriteDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.detailDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDetailDirective([NotNull] ShaderParser.DetailDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.detailDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDetailDirective([NotNull] ShaderParser.DetailDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.alphaFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlphaFuncDirective([NotNull] ShaderParser.AlphaFuncDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.alphaFuncDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlphaFuncDirective([NotNull] ShaderParser.AlphaFuncDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.boolParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolParam([NotNull] ShaderParser.BoolParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.boolParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolParam([NotNull] ShaderParser.BoolParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.intParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntParam([NotNull] ShaderParser.IntParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.intParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntParam([NotNull] ShaderParser.IntParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.numberParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberParam([NotNull] ShaderParser.NumberParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.numberParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberParam([NotNull] ShaderParser.NumberParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.pathParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathParam([NotNull] ShaderParser.PathParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.pathParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathParam([NotNull] ShaderParser.PathParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.cullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCullType([NotNull] ShaderParser.CullTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.cullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCullType([NotNull] ShaderParser.CullTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.waveFormFunctionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWaveFormFunctionType([NotNull] ShaderParser.WaveFormFunctionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.waveFormFunctionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWaveFormFunctionType([NotNull] ShaderParser.WaveFormFunctionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.sortType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortType([NotNull] ShaderParser.SortTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.sortType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortType([NotNull] ShaderParser.SortTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.surfaceParmType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSurfaceParmType([NotNull] ShaderParser.SurfaceParmTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.surfaceParmType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSurfaceParmType([NotNull] ShaderParser.SurfaceParmTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qer_alphaFuncType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQer_alphaFuncType([NotNull] ShaderParser.Qer_alphaFuncTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qer_alphaFuncType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQer_alphaFuncType([NotNull] ShaderParser.Qer_alphaFuncTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3map_lightmapAxisType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQ3map_lightmapAxisType([NotNull] ShaderParser.Q3map_lightmapAxisTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3map_lightmapAxisType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQ3map_lightmapAxisType([NotNull] ShaderParser.Q3map_lightmapAxisTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncSimplifiedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlendFuncSimplifiedType([NotNull] ShaderParser.BlendFuncSimplifiedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncSimplifiedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlendFuncSimplifiedType([NotNull] ShaderParser.BlendFuncSimplifiedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncExplicitSrcType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlendFuncExplicitSrcType([NotNull] ShaderParser.BlendFuncExplicitSrcTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncExplicitSrcType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlendFuncExplicitSrcType([NotNull] ShaderParser.BlendFuncExplicitSrcTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncExplicitDestType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlendFuncExplicitDestType([NotNull] ShaderParser.BlendFuncExplicitDestTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncExplicitDestType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlendFuncExplicitDestType([NotNull] ShaderParser.BlendFuncExplicitDestTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.depthFuncType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDepthFuncType([NotNull] ShaderParser.DepthFuncTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.depthFuncType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDepthFuncType([NotNull] ShaderParser.DepthFuncTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.alphaFuncType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlphaFuncType([NotNull] ShaderParser.AlphaFuncTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.alphaFuncType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlphaFuncType([NotNull] ShaderParser.AlphaFuncTypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
