//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michael/Repos/UrtLib/ShaderLib/Parser/Shader.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	#pragma warning disable 3021
    using System.Globalization;
	using ShaderLib;
	using ShaderLib.Elements;
    using ShaderLib.Elements.Directives;
    using ShaderLib.Elements.Directives.Attributes;
    using ShaderLib.Elements.Directives.ShaderDirectives;
    using ShaderLib.Elements.Directives.ShaderDirectives.General;
    using ShaderLib.Elements.Directives.ShaderDirectives.Q3Map;
    using ShaderLib.Elements.Directives.ShaderDirectives.Qer;
    using ShaderLib.Elements.Directives.StageDirectives;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ShaderParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IShaderListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shaderList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShaderList([NotNull] ShaderParser.ShaderListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shaderList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShaderList([NotNull] ShaderParser.ShaderListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShader([NotNull] ShaderParser.ShaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShader([NotNull] ShaderParser.ShaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStage([NotNull] ShaderParser.StageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStage([NotNull] ShaderParser.StageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shaderDirectiveList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShaderDirectiveList([NotNull] ShaderParser.ShaderDirectiveListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shaderDirectiveList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShaderDirectiveList([NotNull] ShaderParser.ShaderDirectiveListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stageList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStageList([NotNull] ShaderParser.StageListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stageList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStageList([NotNull] ShaderParser.StageListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stageDirectiveList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStageDirectiveList([NotNull] ShaderParser.StageDirectiveListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stageDirectiveList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStageDirectiveList([NotNull] ShaderParser.StageDirectiveListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.shaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShaderDirective([NotNull] ShaderParser.ShaderDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.shaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShaderDirective([NotNull] ShaderParser.ShaderDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.generalDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneralDirective([NotNull] ShaderParser.GeneralDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.generalDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneralDirective([NotNull] ShaderParser.GeneralDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.cullDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCullDirective([NotNull] ShaderParser.CullDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.cullDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCullDirective([NotNull] ShaderParser.CullDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.deformVertexesDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeformVertexesDirective([NotNull] ShaderParser.DeformVertexesDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.deformVertexesDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeformVertexesDirective([NotNull] ShaderParser.DeformVertexesDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.fogParmsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFogParmsDirective([NotNull] ShaderParser.FogParmsDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.fogParmsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFogParmsDirective([NotNull] ShaderParser.FogParmsDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.noMipMapsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoMipMapsDirective([NotNull] ShaderParser.NoMipMapsDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.noMipMapsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoMipMapsDirective([NotNull] ShaderParser.NoMipMapsDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.noPicMipDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPicMipDirective([NotNull] ShaderParser.NoPicMipDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.noPicMipDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPicMipDirective([NotNull] ShaderParser.NoPicMipDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.polygonOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPolygonOffsetDirective([NotNull] ShaderParser.PolygonOffsetDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.polygonOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPolygonOffsetDirective([NotNull] ShaderParser.PolygonOffsetDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.portalDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPortalDirective([NotNull] ShaderParser.PortalDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.portalDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPortalDirective([NotNull] ShaderParser.PortalDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.skyParmsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkyParmsDirective([NotNull] ShaderParser.SkyParmsDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.skyParmsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkyParmsDirective([NotNull] ShaderParser.SkyParmsDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.sortDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortDirective([NotNull] ShaderParser.SortDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.sortDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortDirective([NotNull] ShaderParser.SortDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.tessSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTessSizeDirective([NotNull] ShaderParser.TessSizeDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.tessSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTessSizeDirective([NotNull] ShaderParser.TessSizeDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.lightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLightDirective([NotNull] ShaderParser.LightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.lightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLightDirective([NotNull] ShaderParser.LightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.entityMergableDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntityMergableDirective([NotNull] ShaderParser.EntityMergableDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.entityMergableDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntityMergableDirective([NotNull] ShaderParser.EntityMergableDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.surfaceParmDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSurfaceParmDirective([NotNull] ShaderParser.SurfaceParmDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.surfaceParmDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSurfaceParmDirective([NotNull] ShaderParser.SurfaceParmDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapDirective([NotNull] ShaderParser.Q3mapDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapDirective([NotNull] ShaderParser.Q3mapDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapAlphaGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapAlphaGenDirective([NotNull] ShaderParser.Q3mapAlphaGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapAlphaGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapAlphaGenDirective([NotNull] ShaderParser.Q3mapAlphaGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapAlphaModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapAlphaModDirective([NotNull] ShaderParser.Q3mapAlphaModDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapAlphaModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapAlphaModDirective([NotNull] ShaderParser.Q3mapAlphaModDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBackShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapBackShaderDirective([NotNull] ShaderParser.Q3mapBackShaderDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBackShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapBackShaderDirective([NotNull] ShaderParser.Q3mapBackShaderDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBackSplashDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapBackSplashDirective([NotNull] ShaderParser.Q3mapBackSplashDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBackSplashDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapBackSplashDirective([NotNull] ShaderParser.Q3mapBackSplashDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBaseShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapBaseShaderDirective([NotNull] ShaderParser.Q3mapBaseShaderDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBaseShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapBaseShaderDirective([NotNull] ShaderParser.Q3mapBaseShaderDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBounceDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapBounceDirective([NotNull] ShaderParser.Q3mapBounceDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBounceDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapBounceDirective([NotNull] ShaderParser.Q3mapBounceDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapBounceScaleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapBounceScaleDirective([NotNull] ShaderParser.Q3mapBounceScaleDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapBounceScaleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapBounceScaleDirective([NotNull] ShaderParser.Q3mapBounceScaleDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapClipModelDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapClipModelDirective([NotNull] ShaderParser.Q3mapClipModelDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapClipModelDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapClipModelDirective([NotNull] ShaderParser.Q3mapClipModelDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapCloneShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapCloneShaderDirective([NotNull] ShaderParser.Q3mapCloneShaderDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapCloneShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapCloneShaderDirective([NotNull] ShaderParser.Q3mapCloneShaderDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapColorGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapColorGenDirective([NotNull] ShaderParser.Q3mapColorGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapColorGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapColorGenDirective([NotNull] ShaderParser.Q3mapColorGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapColorModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapColorModDirective([NotNull] ShaderParser.Q3mapColorModDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapColorModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapColorModDirective([NotNull] ShaderParser.Q3mapColorModDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapFancyWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapFancyWaterDirective([NotNull] ShaderParser.Q3mapFancyWaterDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapFancyWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapFancyWaterDirective([NotNull] ShaderParser.Q3mapFancyWaterDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapFogDirDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapFogDirDirective([NotNull] ShaderParser.Q3mapFogDirDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapFogDirDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapFogDirDirective([NotNull] ShaderParser.Q3mapFogDirDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapForceMetaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapForceMetaDirective([NotNull] ShaderParser.Q3mapForceMetaDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapForceMetaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapForceMetaDirective([NotNull] ShaderParser.Q3mapForceMetaDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapForceSunLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapForceSunLightDirective([NotNull] ShaderParser.Q3mapForceSunLightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapForceSunLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapForceSunLightDirective([NotNull] ShaderParser.Q3mapForceSunLightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapFurDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapFurDirective([NotNull] ShaderParser.Q3mapFurDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapFurDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapFurDirective([NotNull] ShaderParser.Q3mapFurDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapGlobalTextureDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapGlobalTextureDirective([NotNull] ShaderParser.Q3mapGlobalTextureDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapGlobalTextureDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapGlobalTextureDirective([NotNull] ShaderParser.Q3mapGlobalTextureDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapIndexedDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapIndexedDirective([NotNull] ShaderParser.Q3mapIndexedDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapIndexedDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapIndexedDirective([NotNull] ShaderParser.Q3mapIndexedDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapInvertDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapInvertDirective([NotNull] ShaderParser.Q3mapInvertDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapInvertDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapInvertDirective([NotNull] ShaderParser.Q3mapInvertDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightImageDirective([NotNull] ShaderParser.Q3mapLightImageDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightImageDirective([NotNull] ShaderParser.Q3mapLightImageDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapAxisDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapAxisDirective([NotNull] ShaderParser.Q3mapLightmapAxisDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapAxisDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapAxisDirective([NotNull] ShaderParser.Q3mapLightmapAxisDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapBrightnessDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapBrightnessDirective([NotNull] ShaderParser.Q3mapLightmapBrightnessDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapBrightnessDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapBrightnessDirective([NotNull] ShaderParser.Q3mapLightmapBrightnessDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapFilterRadiusDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapFilterRadiusDirective([NotNull] ShaderParser.Q3mapLightmapFilterRadiusDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapFilterRadiusDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapFilterRadiusDirective([NotNull] ShaderParser.Q3mapLightmapFilterRadiusDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapGammaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapGammaDirective([NotNull] ShaderParser.Q3mapLightmapGammaDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapGammaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapGammaDirective([NotNull] ShaderParser.Q3mapLightmapGammaDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapMergableDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapMergableDirective([NotNull] ShaderParser.Q3mapLightmapMergableDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapMergableDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapMergableDirective([NotNull] ShaderParser.Q3mapLightmapMergableDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapSampleOffsetDirective([NotNull] ShaderParser.Q3mapLightmapSampleOffsetDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapSampleOffsetDirective([NotNull] ShaderParser.Q3mapLightmapSampleOffsetDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapSampleSizeDirective([NotNull] ShaderParser.Q3mapLightmapSampleSizeDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSampleSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapSampleSizeDirective([NotNull] ShaderParser.Q3mapLightmapSampleSizeDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightmapSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightmapSizeDirective([NotNull] ShaderParser.Q3mapLightmapSizeDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightmapSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightmapSizeDirective([NotNull] ShaderParser.Q3mapLightmapSizeDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightRGBDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightRGBDirective([NotNull] ShaderParser.Q3mapLightRGBDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightRGBDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightRGBDirective([NotNull] ShaderParser.Q3mapLightRGBDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightStyleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightStyleDirective([NotNull] ShaderParser.Q3mapLightStyleDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightStyleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightStyleDirective([NotNull] ShaderParser.Q3mapLightStyleDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapLightSubdivideDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapLightSubdivideDirective([NotNull] ShaderParser.Q3mapLightSubdivideDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapLightSubdivideDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapLightSubdivideDirective([NotNull] ShaderParser.Q3mapLightSubdivideDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoClipDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoClipDirective([NotNull] ShaderParser.Q3mapNoClipDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoClipDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoClipDirective([NotNull] ShaderParser.Q3mapNoClipDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoFastDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoFastDirective([NotNull] ShaderParser.Q3mapNoFastDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoFastDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoFastDirective([NotNull] ShaderParser.Q3mapNoFastDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoFogDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoFogDirective([NotNull] ShaderParser.Q3mapNoFogDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoFogDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoFogDirective([NotNull] ShaderParser.Q3mapNoFogDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoLightmapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoLightmapDirective([NotNull] ShaderParser.Q3mapNoLightmapDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoLightmapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoLightmapDirective([NotNull] ShaderParser.Q3mapNoLightmapDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNonPlanarDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNonPlanarDirective([NotNull] ShaderParser.Q3mapNonPlanarDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNonPlanarDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNonPlanarDirective([NotNull] ShaderParser.Q3mapNonPlanarDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNormalImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNormalImageDirective([NotNull] ShaderParser.Q3mapNormalImageDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNormalImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNormalImageDirective([NotNull] ShaderParser.Q3mapNormalImageDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoTJuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoTJuncDirective([NotNull] ShaderParser.Q3mapNoTJuncDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoTJuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoTJuncDirective([NotNull] ShaderParser.Q3mapNoTJuncDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoVertexLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoVertexLightDirective([NotNull] ShaderParser.Q3mapNoVertexLightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoVertexLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoVertexLightDirective([NotNull] ShaderParser.Q3mapNoVertexLightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoVertexShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoVertexShadowsDirective([NotNull] ShaderParser.Q3mapNoVertexShadowsDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoVertexShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoVertexShadowsDirective([NotNull] ShaderParser.Q3mapNoVertexShadowsDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapOffsetDirective([NotNull] ShaderParser.Q3mapOffsetDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapOffsetDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapOffsetDirective([NotNull] ShaderParser.Q3mapOffsetDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapPatchShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapPatchShadowsDirective([NotNull] ShaderParser.Q3mapPatchShadowsDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapPatchShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapPatchShadowsDirective([NotNull] ShaderParser.Q3mapPatchShadowsDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapRemapShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapRemapShaderDirective([NotNull] ShaderParser.Q3mapRemapShaderDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapRemapShaderDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapRemapShaderDirective([NotNull] ShaderParser.Q3mapRemapShaderDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapRGBGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapRGBGenDirective([NotNull] ShaderParser.Q3mapRGBGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapRGBGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapRGBGenDirective([NotNull] ShaderParser.Q3mapRGBGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapRGBModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapRGBModDirective([NotNull] ShaderParser.Q3mapRGBModDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapRGBModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapRGBModDirective([NotNull] ShaderParser.Q3mapRGBModDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapShadeAngleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapShadeAngleDirective([NotNull] ShaderParser.Q3mapShadeAngleDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapShadeAngleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapShadeAngleDirective([NotNull] ShaderParser.Q3mapShadeAngleDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSkyLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapSkyLightDirective([NotNull] ShaderParser.Q3mapSkyLightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSkyLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapSkyLightDirective([NotNull] ShaderParser.Q3mapSkyLightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSplotchFixDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapSplotchFixDirective([NotNull] ShaderParser.Q3mapSplotchFixDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSplotchFixDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapSplotchFixDirective([NotNull] ShaderParser.Q3mapSplotchFixDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapStyleMarkerDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapStyleMarkerDirective([NotNull] ShaderParser.Q3mapStyleMarkerDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapStyleMarkerDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapStyleMarkerDirective([NotNull] ShaderParser.Q3mapStyleMarkerDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapStyleMarker2Directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapStyleMarker2Directive([NotNull] ShaderParser.Q3mapStyleMarker2DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapStyleMarker2Directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapStyleMarker2Directive([NotNull] ShaderParser.Q3mapStyleMarker2DirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSunDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapSunDirective([NotNull] ShaderParser.Q3mapSunDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSunDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapSunDirective([NotNull] ShaderParser.Q3mapSunDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSunExtDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapSunExtDirective([NotNull] ShaderParser.Q3mapSunExtDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSunExtDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapSunExtDirective([NotNull] ShaderParser.Q3mapSunExtDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSurfaceLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapSurfaceLightDirective([NotNull] ShaderParser.Q3mapSurfaceLightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSurfaceLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapSurfaceLightDirective([NotNull] ShaderParser.Q3mapSurfaceLightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapSurfaceModelDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapSurfaceModelDirective([NotNull] ShaderParser.Q3mapSurfaceModelDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapSurfaceModelDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapSurfaceModelDirective([NotNull] ShaderParser.Q3mapSurfaceModelDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTcGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapTcGenDirective([NotNull] ShaderParser.Q3mapTcGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTcGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapTcGenDirective([NotNull] ShaderParser.Q3mapTcGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTcModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapTcModDirective([NotNull] ShaderParser.Q3mapTcModDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTcModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapTcModDirective([NotNull] ShaderParser.Q3mapTcModDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTerrainDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapTerrainDirective([NotNull] ShaderParser.Q3mapTerrainDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTerrainDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapTerrainDirective([NotNull] ShaderParser.Q3mapTerrainDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTessSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapTessSizeDirective([NotNull] ShaderParser.Q3mapTessSizeDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTessSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapTessSizeDirective([NotNull] ShaderParser.Q3mapTessSizeDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTextureSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapTextureSizeDirective([NotNull] ShaderParser.Q3mapTextureSizeDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTextureSizeDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapTextureSizeDirective([NotNull] ShaderParser.Q3mapTextureSizeDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapTraceLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapTraceLightDirective([NotNull] ShaderParser.Q3mapTraceLightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapTraceLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapTraceLightDirective([NotNull] ShaderParser.Q3mapTraceLightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapVertexScaleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapVertexScaleDirective([NotNull] ShaderParser.Q3mapVertexScaleDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapVertexScaleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapVertexScaleDirective([NotNull] ShaderParser.Q3mapVertexScaleDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapVertexShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapVertexShadowsDirective([NotNull] ShaderParser.Q3mapVertexShadowsDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapVertexShadowsDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapVertexShadowsDirective([NotNull] ShaderParser.Q3mapVertexShadowsDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapVLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapVLightDirective([NotNull] ShaderParser.Q3mapVLightDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapVLightDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapVLightDirective([NotNull] ShaderParser.Q3mapVLightDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapNoFancyWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapNoFancyWaterDirective([NotNull] ShaderParser.Q3mapNoFancyWaterDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapNoFancyWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapNoFancyWaterDirective([NotNull] ShaderParser.Q3mapNoFancyWaterDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3mapCheapWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3mapCheapWaterDirective([NotNull] ShaderParser.Q3mapCheapWaterDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3mapCheapWaterDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3mapCheapWaterDirective([NotNull] ShaderParser.Q3mapCheapWaterDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.editorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEditorDirective([NotNull] ShaderParser.EditorDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.editorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEditorDirective([NotNull] ShaderParser.EditorDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerEditorImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQerEditorImageDirective([NotNull] ShaderParser.QerEditorImageDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerEditorImageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQerEditorImageDirective([NotNull] ShaderParser.QerEditorImageDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerNoCarveDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQerNoCarveDirective([NotNull] ShaderParser.QerNoCarveDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerNoCarveDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQerNoCarveDirective([NotNull] ShaderParser.QerNoCarveDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerTransDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQerTransDirective([NotNull] ShaderParser.QerTransDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerTransDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQerTransDirective([NotNull] ShaderParser.QerTransDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qerAlphaFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQerAlphaFuncDirective([NotNull] ShaderParser.QerAlphaFuncDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qerAlphaFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQerAlphaFuncDirective([NotNull] ShaderParser.QerAlphaFuncDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.stageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStageDirective([NotNull] ShaderParser.StageDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.stageDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStageDirective([NotNull] ShaderParser.StageDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.mapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapDirective([NotNull] ShaderParser.MapDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.mapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapDirective([NotNull] ShaderParser.MapDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.clampMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClampMapDirective([NotNull] ShaderParser.ClampMapDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.clampMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClampMapDirective([NotNull] ShaderParser.ClampMapDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.animMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnimMapDirective([NotNull] ShaderParser.AnimMapDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.animMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnimMapDirective([NotNull] ShaderParser.AnimMapDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.videoMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVideoMapDirective([NotNull] ShaderParser.VideoMapDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.videoMapDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVideoMapDirective([NotNull] ShaderParser.VideoMapDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlendFuncDirective([NotNull] ShaderParser.BlendFuncDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlendFuncDirective([NotNull] ShaderParser.BlendFuncDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.rGBGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRGBGenDirective([NotNull] ShaderParser.RGBGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.rGBGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRGBGenDirective([NotNull] ShaderParser.RGBGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.alphaGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlphaGenDirective([NotNull] ShaderParser.AlphaGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.alphaGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlphaGenDirective([NotNull] ShaderParser.AlphaGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.tcGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTcGenDirective([NotNull] ShaderParser.TcGenDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.tcGenDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTcGenDirective([NotNull] ShaderParser.TcGenDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.tcModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTcModDirective([NotNull] ShaderParser.TcModDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.tcModDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTcModDirective([NotNull] ShaderParser.TcModDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.depthFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDepthFuncDirective([NotNull] ShaderParser.DepthFuncDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.depthFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDepthFuncDirective([NotNull] ShaderParser.DepthFuncDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.depthWriteDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDepthWriteDirective([NotNull] ShaderParser.DepthWriteDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.depthWriteDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDepthWriteDirective([NotNull] ShaderParser.DepthWriteDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.detailDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDetailDirective([NotNull] ShaderParser.DetailDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.detailDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDetailDirective([NotNull] ShaderParser.DetailDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.alphaFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlphaFuncDirective([NotNull] ShaderParser.AlphaFuncDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.alphaFuncDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlphaFuncDirective([NotNull] ShaderParser.AlphaFuncDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.boolParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolParam([NotNull] ShaderParser.BoolParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.boolParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolParam([NotNull] ShaderParser.BoolParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.intParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntParam([NotNull] ShaderParser.IntParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.intParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntParam([NotNull] ShaderParser.IntParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.numberParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberParam([NotNull] ShaderParser.NumberParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.numberParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberParam([NotNull] ShaderParser.NumberParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.pathParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathParam([NotNull] ShaderParser.PathParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.pathParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathParam([NotNull] ShaderParser.PathParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.cullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCullType([NotNull] ShaderParser.CullTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.cullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCullType([NotNull] ShaderParser.CullTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.waveFormFunctionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWaveFormFunctionType([NotNull] ShaderParser.WaveFormFunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.waveFormFunctionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWaveFormFunctionType([NotNull] ShaderParser.WaveFormFunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.sortType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortType([NotNull] ShaderParser.SortTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.sortType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortType([NotNull] ShaderParser.SortTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.surfaceParmType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSurfaceParmType([NotNull] ShaderParser.SurfaceParmTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.surfaceParmType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSurfaceParmType([NotNull] ShaderParser.SurfaceParmTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.qer_alphaFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQer_alphaFuncType([NotNull] ShaderParser.Qer_alphaFuncTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.qer_alphaFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQer_alphaFuncType([NotNull] ShaderParser.Qer_alphaFuncTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.q3map_lightmapAxisType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQ3map_lightmapAxisType([NotNull] ShaderParser.Q3map_lightmapAxisTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.q3map_lightmapAxisType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQ3map_lightmapAxisType([NotNull] ShaderParser.Q3map_lightmapAxisTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncSimplifiedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlendFuncSimplifiedType([NotNull] ShaderParser.BlendFuncSimplifiedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncSimplifiedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlendFuncSimplifiedType([NotNull] ShaderParser.BlendFuncSimplifiedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncExplicitSrcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlendFuncExplicitSrcType([NotNull] ShaderParser.BlendFuncExplicitSrcTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncExplicitSrcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlendFuncExplicitSrcType([NotNull] ShaderParser.BlendFuncExplicitSrcTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.blendFuncExplicitDestType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlendFuncExplicitDestType([NotNull] ShaderParser.BlendFuncExplicitDestTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.blendFuncExplicitDestType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlendFuncExplicitDestType([NotNull] ShaderParser.BlendFuncExplicitDestTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.depthFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDepthFuncType([NotNull] ShaderParser.DepthFuncTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.depthFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDepthFuncType([NotNull] ShaderParser.DepthFuncTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShaderParser.alphaFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlphaFuncType([NotNull] ShaderParser.AlphaFuncTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShaderParser.alphaFuncType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlphaFuncType([NotNull] ShaderParser.AlphaFuncTypeContext context);
}
